name: deploy to branch

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0
      - run: |
          git checkout -b deploy
          zola build
          ls | grep -v public | xargs rm -rf
          mv public/* .
          rmdir public
          git config --global user.email "kirederik@users.noreply.github.com"
          git config --global user.name "Derik Evangelista"
          git add --force .
          git commit -m"[automated commit] update website"
          git push origin deploy

