name: deploy to branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0
      - run: |
          git checkout -b deploy
          zola build
          ls | grep -v public | xargs rm -rf 
          mv public/* .
          rmdir public
          git config --global user.email "github-action"
          git config --global user.name "action bot"
          git add --force .
          git commit -m"update website"
          git push origin deploy
        
